stages:
  - test

test:
  stage: test
  # 将CICD限制在main分支上运行
  only:
    - main
  script:
#    - cd /builds/520021910279/mini-k8s-2023
    - apt-get update
    - apt-get install -y gcc automake autoconf libtool make
    - cd $CI_PROJECT_DIR
    - export PATH=$PATH:/usr/local/bin/etcd:/usr/local/go/bin
    - go env -w GOPROXY=https://goproxy.cn
    - make testPod
    - go test ./test/testFile
    - make kill-all
