apiVersion: v1
kind: Service
metadata:
  name: example-service2
spec:
  clusterIP: 10.181.159.205
  selector:
    app: nginx
    env: prod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
