apiVersion: v1
kind: Service
metadata:
  name: example-service2
spec:
  clusterIP: 10.11.11.12
  selector:
    app: nginx
    env: prod
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8181
